name: Deploy to Vercel

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Vercel
        id: vercel-deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Exact match (uppercase)
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # Exact match (uppercase)
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # Exact match (uppercase)
          scope: ${{ secrets.VERCEL_SCOPE }}  # Must exist in your secrets
          working-directory: ./
      - name: Verify Deployment
        run: |
          if [ "${{ steps.vercel-deploy.outputs.url }}" = "" ]; then
            echo "::error::Deployment failed"
            exit 1
          else
            echo "Deployment URL: ${{ steps.vercel-deploy.outputs.url }}"
          fi